### ISSUE TITLE
Error in payloads module

### ISSUE THREAD

**Issue by sameeripro** [MITRECND/chopshop#67]
Hi Team,

I tried on ubuntu and also on docker but I am getting below error.

Starting ChopShop (Created by MITRE)
Initializing Modules ...
	Initializing module 'payloads'
WARNING: No Parent for payloads providing sslim data
Running Modules ...
Exception in module payloads -- Traceback: 
Traceback (most recent call last):
  File "/usr/local/libexec/chopshop/shop/ChopNids.py", line 565, in handleTcpStreams
    output = code.handleStream(tcpd)
  File "/usr/local/libexec/chopshop/modules/payloads.py", line 145, in handleStream
    handle_bytes(data, color, direction, tcp.module_data)
  File "/usr/local/libexec/chopshop/modules/payloads.py", line 168, in handle_bytes
    chop.prettyprnt(color, data)
  File "/usr/local/libexec/chopshop/shop/ChopHelper.py", line 153, in prettyprnt
    raise TypeError("Unable to create string from inputs")
TypeError: Unable to create string from inputs

**Comment by Mraoul** [comment]
Not sure if you found a work around, but take a look at the verbose-unicode-error-msgs branch. I added some code a while back to handle unicode a bit differently -- I couldn't adequately test the branch out so it was never committed to master.
